// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpwrrvnqeukwbektsmon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwd3Jydm5xZXVrd2Jla3RzbW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjk2OTQsImV4cCI6MjA1Njk0NTY5NH0.ZSfSdwgvKxydweQ2_esymcRoLmgQfemqLFnwzpRcuhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);